### ISSUE TITLE
neogen generate

### ISSUE THREAD

**Issue by ChristianKniep** [neoxygen/neo4j-neogen#13]
Hey there,

I would like to give your tool a try but I guess I am not doing it right.
How to I specify the yml input file? Does it expect a `neogen.yml` file in the current working directory?

Cheers

**Comment by ChristianKniep** [comment]
Oh and while we are at it. The README says `./vendor/bin/neogen` but `neogen` is placed in `./bin/`...

**Comment by ikwattro** [comment]
Hi !

Sorry, the lib is currently in huge refactoring. This should be done by May 7th.

However you can try it by looking at the code used in the test.php file https://github.com/neoxygen/neo4j-neogen/blob/master/test.php

Thanks for your interest in this lib.

**Comment by ChristianKniep** [comment]
OK, no worries. I'll wait for next week to visit it again.
Thx for this, I really looking forward to give it a spin.

**Comment by ikwattro** [comment]
In the meantime you can try Graphgen http://graphgen.neoxygen.io which is neogen but with a visual interface ;-)

**Comment by ChristianKniep** [comment]
I would like to include it within an Cluster-SoftwareStack simulator to mock up a network (CLOS2) even if it is not there. Therefore I need an offline version. :)

**Comment by ikwattro** [comment]
Wow super use case :)

**Comment by ikwattro** [comment]
Forgot to mention that the bin is available if you use the 1.0.8 tag version.

So yes, you need to have a neogen.yml file at the root of the directory
